### ISSUE TITLE
Syntax highlighting doesn't cope with international chars

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#1002]
tmLanguage (that powers GitHub highlighting for F#) doesn't handle international characters well:
```fsharp
  let värde = 123
  let parseÅtgärd (r:ÄrendeRad) (s:string) = 1
```
Same without
```fsharp
  let varde = 123
  let parseAtgard (r:ArendeRad) (s:string) = 1
```

**Comment by guillermooo** [comment]
Sublime will start using .sublime-syntax, so untagging.

**Comment by rneatherway** [comment]
@Krzysztof-Cieslak, does this work in Atom?

**Comment by Krzysztof-Cieslak** [comment]
Looks good, 
![image](https://cloud.githubusercontent.com/assets/5427083/8064576/fd5419a0-0edb-11e5-83dd-f6b633e49ca5.png)
