### ISSUE TITLE
Documentation comments in MonoDevelop are broken since new ToolTip on Linux

### ISSUE THREAD

**Issue by artyomszasa** [fsharp/fsharpbinding#1009]
Opening new issue as the last one was closed yet not fixed.
Old one: https://github.com/fsharp/fsharpbinding/issues/684 

Ever since 2014 aug. Documentation comments are shown as raw text on Linux.
![monodevelop doc comment](https://cloud.githubusercontent.com/assets/843989/7566904/e78ca040-f7f9-11e4-8b59-f42d43f3a390.jpg)

Details:
System: Ubuntu 14.04.2 LTS AMD64
Mono: mono-3.12.0-branch/0849ec7
MonoDevelop: 6.0/da904dee547b83c2ac528ce4ac4167a3376ce7e1, GTK+ 2.24.23 (Ambiance theme)

**Comment by rneatherway** [comment]
The monodevelop support has moved over to http://github.com/fsharp/FSharpMDXS, please report this there.
