### ISSUE TITLE
Adding Glyph to Completion output in fsautocomplete

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsharp/fsharpbinding#1010]
Hello,

I would be interested in adding glyphs to output from completion command in `fsautocomplete`. This would allow me to provide richer autocomplete user experience in Atom (something like ![](https://cloud.githubusercontent.com/assets/69169/6793494/63578990-d182-11e4-988f-2fc4ed3cbccb.png) )

I've created basic implementation on my fork of project (https://github.com/fsharp/fsharpbinding/compare/master...Krzysztof-Cieslak:CompletionType) but it is "breaking" change so I don't know what is procedure for such case.

Also, is there anywhere list of possible glyph values?

**Comment by 7sharp9** [comment]
See: 
https://github.com/fsharp/FSharpMDXS/blob/master/MonoDevelop.FSharpBinding/Services/LanguageService.fs#L124

**Comment by rneatherway** [comment]
@Krzysztof-Cieslak this is a nice idea, and I am completely open to breaking changes where they improve things. We should just inform the vim and sublime guys. Anyway, I have some good news, which is that this repo is being deprecated, and the FSharp.AutoComplete component as of this weekend lives over here: https://github.com/fsharp/FSharp.AutoComplete/. I've also just done a binary release as you asked: https://github.com/fsharp/FSharp.AutoComplete/releases/tag/0.14.0. This has a [fsautocomplete.zip](https://github.com/fsharp/FSharp.AutoComplete/releases/download/0.14.0/fsautocomplete.zip) that you can drop in with your plugin.

So, if you could move this over to the new repo as a PR, with a bump to the version number (perhaps 0.15.0 as it changes the API) and run and check the tests that would be great. I wonder if it would be worth changing the `Glyph` property to a more usable string. Dave, I couldn't quite make sense of the link you posted, why divide by 6?

**Comment by 7sharp9** [comment]
It uses bitfields, don't blame me the F# compiler stores it that way!

**Comment by 7sharp9** [comment]
See: https://github.com/fsharp/fsharp/blob/259e855b69140995056c1f74d58a26b7071ccae5/src/fsharp/vs/ServiceDeclarations.fs#L1184

**Comment by Krzysztof-Cieslak** [comment]
Ok, so I'm closing this issue if we are moving repo.

**Comment by rneatherway** [comment]
@7sharp9 sorry wasn't blaming you! Thanks for the link.

**Comment by kjnilsson** [comment]
This is great - rather than returning the int representing the glyph could
we do the translation on the server side?

**Comment by rneatherway** [comment]
@kjnilsson yes we are just discussing that over at the new PR https://github.com/fsharp/FSharp.AutoComplete/issues/1
