### ISSUE TITLE
Syntax highlighting: Strange output

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#1011]
I haven't looked at why this happens yet. Code is from https://github.com/fsharp/FSharp.AutoComplete/blob/master/FSharp.CompilerBinding/Parser.fs

```fsharp
  let sequence (P p) (P q) = P (fun inp -> 
    [ for (pr, inp') in p inp do
        for (qr, inp'') in q inp' do 
          yield (pr, qr), inp''])
  let sat p = parser { 
    let! v = item 
    if (p v) then return v }
  let char x = sat ((=) x)
  let digit = sat Char.IsDigit    
  let lower = sat Char.IsLower
  let upper = sat Char.IsUpper
  let letter = sat Char.IsLetter
  let nondigit = sat (Char.IsDigit >> not)
  let whitespace = sat (Char.IsWhiteSpace)
  let alphanum = parser { 
    return! letter
    return! digit }  
  let rec word = parser {
    return []
    return! parser {
      let! x = letter
      let! xs = word
      return x::xs } }
  let string (str:string) = 
    let chars = str.ToCharArray() |> List.ofSeq
    let rec string' = function
      | [] -> result []
      | x::xs -> parser { 
          let! y = char x
          let! ys = string' xs 
          return y::ys }
```

Also reported at https://github.com/fsharp/sublime-fsharp-package/issues/1 because it needs to be fixed in both places. Here for GitHub and there for Sublime.

**Comment by guillermooo** [comment]
Sublime will start using the new .sublime-syntax, so I don't think this will be fixed in any update to ST.

**Comment by rneatherway** [comment]
Moved to Atom at https://github.com/fsprojects/atom-fsharp/issues/57, which will now be used by Github.

**Comment by rojepp** [comment]
@rneatherway Has linguist been updated accordingly?

**Comment by rneatherway** [comment]
I have submitted a PR to linguist at https://github.com/github/linguist/pull/2445

**Comment by rojepp** [comment]
Great, thanks.
