### ISSUE TITLE
Tutorial creates empty project

### ISSUE THREAD

**Issue by darkoverlordofdata** [fsharp/fsharpbinding#1014]
I thought I would try using MonoDevelop to learn F#. Everything installed ok, I have fsharp,  MD 5.9.4 installed, and the F# language plugin. When I create the F# Tutorial project, it creates without error, but all it creates is a folder and a .sln, nothing else. Where is the tutorial?

**Comment by dsyme** [comment]
Hi @darkoverlordofdata - This repo has now been split into constituent parts, please move this issue to https://github.com/fsharp/xamarin-monodevelop-fsharp-addin, thanks!

**Comment by darkoverlordofdata** [comment]
Well, I clicked on the link provided by the plugin from inside MonoDevelop.
Why is everyone connected to Mono always so unhelpful? Everytime I run into
an issue, all I get is a runaround.
Go ahead and close this. I've about had it with MonoDevelop - it barley
works on Linux.
