### ISSUE TITLE
fsautocomplete will not start under mono 3.2.8 in Ubuntu/Linux Trusty

### ISSUE THREAD

**Issue by oivvio** [fsharp/fsharpbinding#1018]
Sorry if this is the right place for this kind of report.

I've installed fsharpbinding for emacs via MELPA as per the instructions in the README.

When opening a fsharp script file I get 

    Failed to start fsautocomplete (Failed to launch: 'mono ~/.emacs.d/elpa/fsharp-mode-20150604.1028/bin/fsautocomplete.exe'). Disabling intellisense. To reenable, set fsharp-ac-intellisense-enabled to t.

To investigate further I run the  `mono .emacs.d/elpa/fsharp-mode-20150604.1028/bin/fsautocomplete.exe`  on the command line and get the following dump:

    Invalid type Microsoft.FSharp.Compiler.SourceCodeServices.FSharpProjectFileInfo for instance field FSharp.InteractiveAutocomplete.Main+files@464:p

    Unhandled Exception:
    System.TypeLoadException: Could not load type 'FSharp.InteractiveAutocomplete.Main+files@464'  from assembly 'fsautocomplete, Version=0.18.0.0, Culture=neutral, PublicKeyToken=null'.
    at FSharp.InteractiveAutocomplete.Main.entry (System.String[] args) [0x00000] in <filename  unknown>:0
    [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type
    'FSharp.InteractiveAutocomplete.Main+files@464' from assembly 'fsautocomplete, Version=0.18.0.0, Culture=neutral, PublicKeyToken=null'.
    at FSharp.InteractiveAutocomplete.Main.entry (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by dsyme** [comment]
Hi @oivvio - did you find a solution for this or move the issue elsewhere? It may be you need to upgrade to a later Mono.
