### ISSUE TITLE
FSX script crashing fsautocomplete.

### ISSUE THREAD

**Issue by xenocons** [fsharp/fsharpbinding#1019]
To reproduce the issue,

Create a .fsx file somewhere else, and put the contents as:
```
#if INTERACTIVE
#I @"C:\Users\user\Documents\Visual Studio 2013\Projects\test\";;
#endif
```

Save this file, and close emacs, then load emacs again, then load this file, you will see fsautocomplete.exe crash with something like the following:
```
Unhandled Exception: System.Exception: Exception when getting check options for 'c:\Users\user\Desktop\test.fsx'
.Details: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at FSharp.CompilerBinding.LanguageService.GetScriptCheckerOptions(String fileName, String projFilename, String source) in C:\Users\user\.emacs.d\fsharpbinding\FSharp.CompilerBinding\LanguageService.fs:line 299
```
Additionally, using fsautocomplete.exe and parsing the above file will cause the same exception.

I think it could perhaps be that the version 12 of the framework stuff is not in VS2015's version of F#? I tried this from a fresh elpa install of fsharp-mode.

Edit: Now that i think about it, this is probably due to CompilerServices not using .NET 4.6 yet?

**Comment by rneatherway** [comment]
Right, that is correct. FSAC doesn't currently support F# 4.0 and/or VS 2015. We are looking at how best to do this. It's difficult because other users of msbuild (e.g. Visual Studio and xbuild on Mono) get to distribute their own installation of msbuild and target files and don't need to worry about supporting different installations.

By the way, this repo is no longer active, see https://github.com/fsharp/fsharpbinding/blob/master/README.md
