### ISSUE TITLE
fsautocomplete.exe not run with mono 3.2.8

### ISSUE THREAD

**Issue by MichaelKazarian** [fsharp/fsharpbinding#1021]
I'm use `mono 3.2.8` on Ubuntu 14.04 64-bit and get next error:

Invalid type Microsoft.FSharp.Compiler.SourceCodeServices.FSharpProjectFileInfo for instance field FSharp.InteractiveAutocomplete.Main+files@464:p

Unhandled Exception:
System.TypeLoadException: Could not load type 'FSharp.InteractiveAutocomplete.Main+files@464' from assembly 'fsautocomplete, Version=0.18.0.0, Culture=neutral, PublicKeyToken=null'.
  at FSharp.InteractiveAutocomplete.Main.entry (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'FSharp.InteractiveAutocomplete.Main+files@464' from assembly 'fsautocomplete, Version=0.18.0.0, Culture=neutral, PublicKeyToken=null'.
  at FSharp.InteractiveAutocomplete.Main.entry (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by rneatherway** [comment]
This repository is now [deprecated](https://github.com/fsharp/fsharpbinding/blob/master/CONTRIBUTING.md). [FsAutoComplete requires at least mono >= 3.10](https://github.com/fsharp/FsAutoComplete).
