### ISSUE TITLE
Question on error

### ISSUE THREAD

**Issue by alxest** [fsharp/fsharpbinding#1022]
I was using fsharp on windows with VS and trying to move it to OS X.
While xbuild compile and mono run works on OS X, fsharp-mode's intellisense gives me some error.
The first error says that :
~~~
The type 'IEnumerable`1' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
~~~
Below is an minimal example I made.
https://github.com/alxest/fsharp_emacs_test
Version of software I use is :
~~~
project/for_upload - [master] » mono --version
Mono JIT compiler version 4.0.1 ((detached/ed1d3ec Tue May 26 17:22:37 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
project/for_upload - [master] » fsharpc
F# Compiler for F# 3.1 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

error FS0207: No inputs specified
project/for_upload - [master] » xbuild -v
XBuild Engine Version 12.0
Mono, Version 4.0.1.0
Copyright (C) 2005-2013 Various Mono authors
MSBUILD: error MSBUILD0000: Project file '-v' not found.
~~~
emacs 24.3
installed fsharp-mode by MELPA about 2 weeks ago.

I have googled a bit and tried to add some references to App.config but it didn't work.
Thank you!

**Comment by rneatherway** [comment]
Hi, thanks for reporting. This repo is now deprecated, and the emacs support has moved to https://github.com/fsharp/emacs-fsharp-mode. There will soon be a new release of the mode with updated project file parsing, which may fix this issue. Install it from MELPA and check again later this week. If it doesn't, please create a new issue at the other repo.

**Comment by alxest** [comment]
@rneatherway Thanks a lot!

**Comment by alxest** [comment]
@rneatherway It seems the problem is indeed solved!
