### ISSUE TITLE
Missing type info tooltips in Lubuntu 14.04

### ISSUE THREAD

**Issue by o7g8** [fsharp/fsharpbinding#1024]
Hi,

Type info tooltips are missing (no tooltip is shown) in MonoDevelop 5.10 / F# Language Binding 5.5.0 / Mono 4.2.3.4-0xamarin2 / fsharp 4.0.0.3-0xamarin1
All the software is installed from "http://download.mono-project.com/repo/debian wheezy main" and is up to date. F# Language Binding is installed from MonoDevelop.

It seems that other people have the issue as well: https://www.reddit.com/r/fsharp/comments/49z6jv/tooltips_in_monodevelop_are_they_working_for_you/

**Comment by 7sharp9** [comment]
This is the old depreciated repo, any F# addin issues should be raised on bugzilla, under the component F#addin.  Thanks!

**Comment by o7g8** [comment]
Thank you, Dave!
I have created https://bugzilla.xamarin.com/show_bug.cgi?id=40264

Oleg
