### ISSUE TITLE
Auto-completion for fsx files stops working

### ISSUE THREAD

**Issue by jkaye2012** [fsharp/fsharpbinding#1026]
Hey there,

I'm experience a strange issue with .fsx files and auto-completion. I'm not 100% sure how to reproduce this issue, but whenever I open a new fsx file in Emacs (one that did not exist before), auto-complete stops working for ALL fsx buffers. Similarly, when working in an fsx buffer (with auto-complete working), if I delete all text from the buffer, the same issue seems to occur. Any idea what could be causing this?

**Comment by jkaye2012** [comment]
Sorry, just realized that this is no longer an active project.

**Comment by dsyme** [comment]
Did you find the right place to report this? thanks

**Comment by jkaye2012** [comment]
Yup, all set. I created a new issue with more information in fsharp-mode.
