### ISSUE TITLE
Implement the ability to move an F# file up and down in the project tree with keyboard and context menu.

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fsharpbinding#135]
I created this issue so that **anyone** that wants to, can implement it.  I think its an important feature because manually editing the fsproj is not ideal to say the least.  

Thanks to @mhutch for these pointers of what's required:

This will be a fair bit of work in MonoDevelop.Core and
MonoDevelop.Ide, unfortunately.
1. The first part is infrastructural - you would need to make it so that changes to the order of the items in the project.Items collection is reflected when serializing the project file. It currently tries to find existing items and update them, then add any new items into existing groups [(MSBuildProjectHandler)](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Formats.MSBuild/MSBuildProjectHandler.cs#L1265)
   
   CAVEAT - you could probably work around this by removing the items, saving the project, then re-adding them in the desired order. But this may have undesired side effects.
2. The second part is displaying it in the UI. The tree node builders currently sort all the nodes by name though this is overridable [(NodeBuilder)](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/NodeBuilder.cs#L134) So I'd suggest adding some kind of project.HasSignificantFileOrder property, then if this were set, the ProjectFolderNodeBuilder could sort the items appropriately.
3. The third part is drag-n-drop. The ProjectFileCommandHandler would have to override the overload of OnMultipleNodeDrop that takes a DropPosition to it can accept drops before/after it [(NodeCommandHandler.cs)](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/NodeCommandHandler.cs#L250) It currently only allows dropping files _onto_ it for grouping [(ProjectFileNodeBuilder.cs)](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs#L258) and then it would have to alter the order of the files in the project correspondingly and trigger a save.

**Comment by norru** [comment]
Newbie to F# here. Doesn't seem to work for folders. Workaround appears to be to name folders _001_subproject, __002_anothersubproject and so on. In 2016? Bloody ugly,

**Comment by OnorioCatenacci** [comment]
If you want assistance @norru you may want to provide some details.  Such as which version of Xamarin Studio you're working with, which OS, etc. etc. etc.

**Comment by 7sharp9** [comment]
This is the old repo, please log issue via bugzilla: https://bugzilla.xamarin.com/enter_bug.cgi?product=Xamarin%20Studio using the component F# Addin with full details of the issue and reproduction steps.

Thanks!
