### ISSUE TITLE
Can't do code completion in C# when types are defined in F#

### ISSUE THREAD

**Issue by mkrueger** [fsharp/fsharpbinding#156]
See https://bugzilla.xamarin.com/show_bug.cgi?id=12304

That's one reason why the F# binding needs a nrefactory bridge anyways. But as a work around you could add something like that to the f# binding addin definition:

https://gist.github.com/mkrueger/5617435

That will track the .dll output and add the .dll to the code completion - but it's just a work around. The real solution is the nrefactory bridge.

**Comment by 7sharp9** [comment]
Fixed, yay
