### ISSUE TITLE
VS2012 .fsproj files upgraded to VS2013 don't work in Xamarin Studio

### ISSUE THREAD

**Issue by ovatsus** [fsharp/fsharpbinding#249]
Xamarin Studio 4.1 didn't work with VS2012 .fsproj files upgraded to VS2012, but https://github.com/mono/monodevelop/pull/407 fixed that, and XS 4.2.x and 4.1.13 include that fix, but unfortunately it still doesn't work. If you build MonoDevelop from source from the equivalent tags, it does work, though. What can we do to try to fix this?

Now that VS2013 RTM is out, people are starting to hit this problem (see for example https://github.com/dungpa/fantomas/issues/104, and there have also been a couple of twitter threads about this)

Note: projects first created in VS2013 have an additional problem (the ToolsVersion=12), the fix for that is https://github.com/mono/monodevelop/pull/447 but it hasn't been merged yet

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#30
