### ISSUE TITLE
Autocompletion tooltip doesn't display the type of fields

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#498]
![screenshot 2014-04-23 22 58 06](https://cloud.githubusercontent.com/assets/445888/2783205/1743bede-cb2a-11e3-89ba-31632bb3e6df.png)

In this case, I would have expected `Func<Document, CancellationToken, IRefactoringContext>`

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#28
