### ISSUE TITLE
Tooltip left edge is off screen

### ISSUE THREAD

**Issue by brodyberg** [fsharp/fsharpbinding#542]
Using Xamarin Studio 4.2.4 (build 35) on OS X Mavericks 10.9.2 on a Mac Book Air when I open some tool tips they will display with the left portion offscreen. See included screenshot. 
![screen shot 2014-05-07 at 6 30 47 pm](https://cloud.githubusercontent.com/assets/151955/2910965/eebb01a2-d650-11e3-94da-ba7d9438b812.png)

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#27
