### ISSUE TITLE
Tooltip exceeds total width of screen

### ISSUE THREAD

**Issue by brodyberg** [fsharp/fsharpbinding#543]
Using Xamarin Studio 4.2.4 (build 35) on OS X Mavericks 10.9.2 on a Mac Book Air when some tooltips display their width is greater than 100% of the screen width. 

Please see attached screenshot. 
![screen shot 2014-05-07 at 6 31 17 pm](https://cloud.githubusercontent.com/assets/151955/2910980/4621e2a8-d651-11e3-8d43-a464ac9a0e3d.png)

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#26
