### ISSUE TITLE
Monodevelop tests fail on Windows

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#553]
This is probably a binding redirect issue with FsUnit:

> System.MissingMethodException : Method not found: 'Void FsUnit.TopLevelOperators.should(Microsoft.FSharp.Core.FSharpFunc`2<!!0, !!0, System.Object)'

This is when running the tests from Xamarin Studio 5.0 (build 866).

**Comment by 7sharp9** [comment]
Fixed in FSharpMDXS
