### ISSUE TITLE
Rename operation offered for external dependencies

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#560]
Minor bug: 
```FSharp
let a = System.String.Empty
```

In XS, the rename refactoring is offered for `Empty` with an ArgumentNullException if you try to invoke the command

**Comment by 7sharp9** [comment]
Will be addressed in XS6 as we use a new chunk of rename refactoring code.

**Comment by 7sharp9** [comment]
This is fixed in MD roslyn branch.
