### ISSUE TITLE
Rename refactoring: Renaming module breaks references

### ISSUE THREAD

**Issue by psfblair** [fsharp/fsharpbinding#587]
When renaming a module the refactoring will rename the file accordingly if I ask it to. However, the references to the module in other F# projects do not update accordingly.

(Xamarin Studio 5.0.1, Mac OS X)

**Comment by 7sharp9** [comment]
Ooops, this has been dormant for a while

**Comment by 7sharp9** [comment]
This should be fixed in XS 6.0~ versions
