### ISSUE TITLE
Emacs phrase eval

### ISSUE THREAD

**Issue by xenocons** [fsharp/fsharpbinding#593]
Hello,

I am not sure if this is a bug or a limitation, or perhaps I need to post it as a feature request.

It seems when evaluating a block of code using C-M-x, the attribute is not included. 

E.g.
```
[<Struct>] 
type x =
  val y:int
```
Placing the cursor after the 'int' and doing C-M-x sends 'type x = val y : int' to the top level, which is parsed as a class as it is missing the struct attribute.

Let me know if you need more info.

Edit: fixed attribute escaping

**Comment by rneatherway** [comment]
Now at https://github.com/fsharp/emacs-fsharp-mode/pull/6
