### ISSUE TITLE
NUnit test window command 'Show test source code' is disabled

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#650]
I haven't looked into what it would take to fix it yet.
This would probably be fixed with an implementation for #647
![screenshot 2014-07-12 07 20 29](https://cloud.githubusercontent.com/assets/445888/3560700/4cac10e2-0984-11e4-8381-b982c1f49e62.png)

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#24
