### ISSUE TITLE
Xamarin Studio on Windows ignores F# compiler path

### ISSUE THREAD

**Issue by buybackoff** [fsharp/fsharpbinding#667]
I have installed Scala and Xamarin Studio started to use fsc from Scala distribution to compile F# projects when I uncheck "Use MsBuild" box in project settings. 

When I uncheck "Use default" in Options -> F# Settings -> F# Default Compiler nothing happens. (I reopened Xamarin Studio several times).

Where the default path is stored?

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#23
