### ISSUE TITLE
VFPT language service

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#669]
This is a discussion issue for VFPT integration. 
So far, we've reached the conclusion that we should use the Language service from VFPT. 
This makes sense, in that we don't want two language services running at the same time, for both stability and performance reasons. 

Their LanguageService has had some methods removed: 

* GetDeclarations
* GetToolTip
* GetDeclarationLocation
* GetMethods

Basically the methods where we use `Parser.fs`.

If we are to use their Language service, we need to either do a PR with these added, or do a PR with check results and parse results exposed, so we can implement these on our end. 
The problem with implementing these in their language service is that our implementation of these depend on `Parser.fs`...

**Comment by 7sharp9** [comment]
I think we'll just close this for now.  Its been dead for a year :-)
