### ISSUE TITLE
Add categorised completion to aid productivity

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fsharpbinding#672]
Im adding this for implementation visibility and to record upstream changes that are outstanding.

Heres what the current prototype looks like:

![proto completion](https://cloud.githubusercontent.com/assets/588746/3629092/1f21d496-0e9c-11e4-9442-35627a33350c.gif)

Heres an link to an upstream required change:
https://github.com/fsharp/FSharp.Compiler.Service/pull/182

**Comment by 7sharp9** [comment]
Done.

**Comment by praeclarum** [comment]
Awesome!
