### ISSUE TITLE
Azure Mobile Services throws error in F# projects

### ISSUE THREAD

**Issue by rachelreese** [fsharp/fsharpbinding#680]
Steps to reproduce: 
- Create new F# iOS App. 
- Add Azure Mobile Services component (right-click Components folder > Get More Components..) 
- Attempt to connect service by adding the following in `AppDelegate.fs`:

    `let MobileService = new Microsoft.WindowsAzure.MobileServices.MobileServiceClient("", "")`

[It fails whether you have empty values or correct values there.]

Result: 
Error FS1108: The type 'Uri' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (FS1108)

Also, uploaded basic breaking code here: https://github.com/rachelreese/AzureMobileServicesTest

**Comment by 7sharp9** [comment]
This is an issue with pcl implicit references for been type checked, should be fixed in XS ~6.0, closing for now as its been dormant for a while too.
