### ISSUE TITLE
iOS Unified API templates don't work

### ISSUE THREAD

**Issue by fabiogaragiola** [fsharp/fsharpbinding#727]
If I create a new project using any of the new iOS Unified API templates, XS complains that the namespaces or modules *UIKit* and *Foundation* are not defined despite Xamarin.iOS being present in the reference list. As a workaround I remove the reference and add it back using the DLL in  
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/  
That do the trick but when I try to compile the project some errors pop up even if the code seems to be perfectly fine:

![code](https://cloud.githubusercontent.com/assets/6490745/4239479/71566612-39e1-11e4-80fb-6413e0e921f3.png)

**Comment by fabiogaragiola** [comment]
@7sharp9, this issue is solved in the current add-in release with Xamarin Studio 5.7. I believe it can be closed.

**Comment by 7sharp9** [comment]
Ok cool, Ill close it.
