### ISSUE TITLE
Clean up FSharp.CompilerBinding agent API

### ISSUE THREAD

**Issue by rneatherway** [fsharp/fsharpbinding#772]
Comment in FSharp.AutoComplete/Program.fs:

// TODO: Clean up the API these options are being generated to call
//
// That API is in FSharp.CompilerBinding.LanguageService.
// 1. It expects a Target Framework, but *only* for FSI as
//    FCS is *rumoured* not to return references including FSharp.Core
//    and it uses the framework to guess where it is.
//    We will just use 4.5.
// 2. The CompileFiles just get added to the options, so we will do that
//    here and then pass in an empty array of CompileFiles.

Any changes will also affect monodevelop binding.

**Comment by 7sharp9** [comment]
I removed the XS label as this is no longer an issue there as its "evolving"

**Comment by rneatherway** [comment]
This issue was moved to fsharp/FSharp.AutoComplete#17
