### ISSUE TITLE
Trouble building monodevelop

### ISSUE THREAD

**Issue by liammclennan** [fsharp/fsharpbinding#792]
> ./configure.sh
> make

/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/Services/LanguageService.fs(134,23): warning FS0044: This construct is deprecated. Use RawGenerator directly
/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs(84,89): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs(85,93): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs(116,15): warning FS0044: This construct is deprecated
/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs(440,46): error FS0039: The field, constructor or member 'GetProjectsContainingFile' is not defined
	Task "Fsc" execution -- FAILED
	Done building target "CoreCompile" in project "/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj".-- FAILED
Done building project "/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj".-- FAILED

Build FAILED.

Warnings:

/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Mono.Debugging, Version=0.0.0.0, Culture=neutral, PublicKeyToken=5e9ce85b0923c84f' not resolved
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Mono.Debugging, Version=0.0.0.0, Culture=neutral, PublicKeyToken=5e9ce85b0923c84f' not resolved

/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj (default targets) ->
/usr/lib/mono/4.0/Microsoft.FSharp.Targets (CoreCompile target) ->

	/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/Services/LanguageService.fs(134,23): warning FS0044: This construct is deprecated. Use RawGenerator directly
	/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs(116,15): warning FS0044: This construct is deprecated

Errors:

/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj (default targets) ->
/usr/lib/mono/4.0/Microsoft.FSharp.Targets (CoreCompile target) ->

	/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs(84,89): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
	/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpLanguageBinding.fs(85,93): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
	/home/liam/work/fsharpbinding/monodevelop/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs(440,46): error FS0039: The field, constructor or member 'GetProjectsContainingFile' is not defined

	 4 Warning(s)
	 3 Error(s)

Time Elapsed 00:00:06.8572240
make: *** [build] Error 1

**Comment by 7sharp9** [comment]
Is this still an issue?  I believe some #defines were added that might of fixed this for older versions.

**Comment by 7sharp9** [comment]
Closing as FSharpMDXS repo will fix any further issues, if any please log
