### ISSUE TITLE
Building monodevelop:  FSharp.Core.sigdata not found alongside FSharp.Core

### ISSUE THREAD

**Issue by aolney** [fsharp/fsharpbinding#797]
Seems like this should have been fixed:

https://github.com/fsharp/FSharp.Compiler.Service/issues/38

Using 
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-7)
F# Compiler for F# 3.1 (Open Source Edition)

op$ ./configure.sh 
Configuring...
MonoDevelop F# add-in configuration script
------------------------------------------
MonoDevelop binaries found at: /usr/lib/monodevelop
Detected version: 5.5
Getting nuget packages...
Installing 'Fantomas 1.5.0'.
Installing 'FSharp.Compiler.Service 0.0.62'.
Successfully installed 'Fantomas 1.5.0'.
Installing 'Mono.Cecil 0.9.5.4'.
Successfully installed 'Mono.Cecil 0.9.5.4'.
Installing 'FSharp.Compiler.CodeDom 0.9.1'.
Successfully installed 'FSharp.Compiler.CodeDom 0.9.1'.
Installing 'ExtCore 0.8.43'.
Successfully installed 'ExtCore 0.8.43'.
Installing 'FSharp.Compiler.Service 0.0.73'.
Installing 'FsUnit 1.2.1.0'.
Successfully installed 'FsUnit 1.2.1.0'.
Installing 'NUnit 2.6.2'.
Successfully installed 'NUnit 2.6.2'.
Successfully installed 'FSharp.Compiler.Service 0.0.62'.
Successfully installed 'FSharp.Compiler.Service 0.0.73'.
aolney@monkamu:~/Downloads/fsharpbinding-master/monodevelop$ make
(cd MonoDevelop.FSharpBinding && xbuild MonoDevelop.FSharp.mac-linux.fsproj /p:Configuration=Debug)
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 11/8/2014 10:01:13 AM.
__________________________________________________
Project "/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj" (default target(s)):
	Target RestorePackages:
		Executing: mono --runtime=v4.0.30319 ./.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "./"
		Restoring NuGet packages...
		To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
		Created directory "../bin/mac-linux/Debug/"
		Created directory "obj/Debug/"
	Target ResolveProjectReferences:
		Project "/home/aolney/Downloads/fsharpbinding-master/FSharp.CompilerBinding/FSharp.CompilerBinding.fsproj" (default target(s)):
			Target RestorePackages:
				Executing: mono --runtime=v4.0.30319 ../monodevelop/MonoDevelop.FSharpBinding/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "../monodevelop/MonoDevelop.FSharpBinding/"
				Restoring NuGet packages...
				To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
				Created directory "bin/Debug/"
				Created directory "obj/Debug/"
			Target CopyFilesMarkedCopyLocal:
				Copying file from '/usr/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll' to '/home/aolney/Downloads/fsharpbinding-master/FSharp.CompilerBinding/bin/Debug/FSharp.Core.dll'
				Copying file from '/home/aolney/Downloads/fsharpbinding-master/lib/mono.cecil/Mono.Cecil.dll' to '/home/aolney/Downloads/fsharpbinding-master/FSharp.CompilerBinding/bin/Debug/Mono.Cecil.dll'
				Copying file from '/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/packages/FSharp.Compiler.Service.0.0.73/lib/net45/FSharp.Compiler.Service.dll' to '/home/aolney/Downloads/fsharpbinding-master/FSharp.CompilerBinding/bin/Debug/FSharp.Compiler.Service.dll'
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target CoreCompile:
				Tool /usr/lib/cli/fsharp/fsc.exe execution started with arguments: -o:obj/Debug/FSharp.CompilerBinding.dll -g --debug:full --noframework --define:DEBUG --optimize- --tailcalls- -r:/usr/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll -r:/usr/lib/mono/4.5/mscorlib.dll -r:/usr/lib/mono/4.5/System.dll -r:/usr/lib/mono/4.5/System.Numerics.dll -r:../lib/mono.cecil/Mono.Cecil.dll -r:../monodevelop/MonoDevelop.FSharpBinding//packages/FSharp.Compiler.Service.0.0.73/lib/net45/FSharp.Compiler.Service.dll -r:/usr/lib/mono/4.5/System.Core.dll --target:library --warn:2 --warnaserror:76 --fullpaths --flaterrors --highentropyva- CodeGeneration.fs Utils.fs Digraph.fs OrderAssemblyReferences.fs CompilerLocationUtils.fs Parser.fs LanguageService.fs InterfaceStubGenerator.fs 
				F# Compiler for F# 3.1 (Open Source Edition)
				Freely distributed under the Apache 2.0 Open Source License
: error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core
: error FS0229: Error opening binary file '/usr/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core
: error FS3160: Problem reading assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Error opening binary file '/usr/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core
			Task "Fsc" execution -- FAILED
			Done building target "CoreCompile" in project "/home/aolney/Downloads/fsharpbinding-master/FSharp.CompilerBinding/FSharp.CompilerBinding.fsproj".-- FAILED
		Done building project "/home/aolney/Downloads/fsharpbinding-master/FSharp.CompilerBinding/FSharp.CompilerBinding.fsproj".-- FAILED
		Project "/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/MonoDevelop.FSharp.Gui.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Debug Platform: AnyCPU
				Created directory "bin/Debug/"
				Created directory "obj/Debug/"
			Target CopyNonResxEmbeddedResources:
				Copying file from '/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/gtk-gui/gui.stetic' to '/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/obj/Debug/MonoDevelop.FSharp.Gui.gtk-gui.gui.stetic'
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target CoreCompile:
				Tool /usr/bin/mcs execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/FSharpBinding.Gui.dll /resource:obj/Debug/MonoDevelop.FSharp.Gui.gtk-gui.gui.stetic,gui.stetic gtk-gui/generated.cs FSharpCompilerOptionsWidget.cs FSharpSettingsWidget.cs gtk-gui/MonoDevelop.FSharp.Gui.FSharpCompilerOptionsWidget.cs gtk-gui/MonoDevelop.FSharp.Gui.FSharpSettingsWidget.cs obj/Debug/.NETFramework,Version=v4.5.AssemblyAttribute.cs /target:library /checked+ /reference:/usr/lib/mono/4.5/System.dll /reference:/usr/lib/mono/4.5/System.Data.dll /reference:/usr/lib/mono/4.5/System.Xml.dll /reference:/usr/lib/mono/4.5/Mono.Posix.dll /reference:/usr/lib/cli/pango-sharp-2.0/pango-sharp.dll /reference:/usr/lib/cli/atk-sharp-2.0/atk-sharp.dll /reference:/usr/lib/cli/gdk-sharp-2.0/gdk-sharp.dll /reference:/usr/lib/cli/gtk-sharp-2.0/gtk-sharp.dll /reference:/usr/lib/cli/glib-sharp-2.0/glib-sharp.dll /reference:/usr/lib/mono/4.5/System.Core.dll /warn:4
			Target DeployOutputFiles:
				Copying file from '/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/obj/Debug/FSharpBinding.Gui.dll.mdb' to '/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/bin/Debug/FSharpBinding.Gui.dll.mdb'
				Copying file from '/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/obj/Debug/FSharpBinding.Gui.dll' to '/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/bin/Debug/FSharpBinding.Gui.dll'
		Done building project "/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/Gui/MonoDevelop.FSharp.Gui.csproj".
	Task "MSBuild" execution -- FAILED
	Done building target "ResolveProjectReferences" in project "/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj".-- FAILED
Done building project "/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj".-- FAILED

Build FAILED.
Errors:

/home/aolney/Downloads/fsharpbinding-master/monodevelop/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.mac-linux.fsproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
/home/aolney/Downloads/fsharpbinding-master/FSharp.CompilerBinding/FSharp.CompilerBinding.fsproj (default targets) ->
/usr/lib/mono/4.0/Microsoft.FSharp.Targets (CoreCompile target) ->

	: error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core
	: error FS0229: Error opening binary file '/usr/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core
	: error FS3160: Problem reading assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Error opening binary file '/usr/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core

	 0 Warning(s)
	 3 Error(s)

Time Elapsed 00:00:06.6662060
Makefile:35: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by 7sharp9** [comment]
Im not sure if theres anything to do here so closing for now.
