### ISSUE TITLE
sublime text - add/change build scripts for non-Windows platforms

### ISSUE THREAD

**Issue by matematicapentrutoti** [fsharp/fsharpbinding#832]
I'm unable to build FSharp.sublime-package.
first -- the https://bitbucket.org/guillermooo/fsac/downloads/fsautocomplete.zip is no longer valid
the new link is https://bitbucket.org/guillermooo/fsac/downloads/fsac.zip
anyway this step of getting the zip file is useless because you can compile yourself from this repo.
after solving this issue publish.sh can't find the builder.py file.

python: can't open file 'builder.py': [Errno 2] No such file or directory

 i was able to replace it with an older, deleted file from repo history, but it does not working!

**Comment by guillermooo** [comment]
Using FAKE now. Life's good! :sunglasses:
