### ISSUE TITLE
sublime text: building projects

### ISSUE THREAD

**Issue by guillermooo** [fsharp/fsharpbinding#839]
@rneatherway Any plans on implementing msbuild discovery in fsac?

**Comment by rneatherway** [comment]
This is in FSharp.AutoComplete: https://github.com/fsharp/FSharp.AutoComplete/blob/master/FSharp.AutoComplete/Program.fs#L135

Currently it just finds fsc and fsi. We could add support for finding msbuild, the logic in emacs works pretty well.

**Comment by rneatherway** [comment]
Apparently I never merged that prototype, which also finds msbuild. Issue opened: https://github.com/fsharp/FSharp.AutoComplete/issues/23
