### ISSUE TITLE
Backticked identifiers not handled in GitHub syntax highlighting

### ISSUE THREAD

**Issue by latkin** [fsharp/fsharpbinding#882]
Based on [this](https://github.com/github/linguist/issues/1746) I understand this repo now contains definitions used for GitHub highlighting of F#, namely [here](https://github.com/fsharp/fsharpbinding/blob/master/sublimetext/FSharp/FSharp.tmLanguage).

Double backtick identifiers seem to mess up GitHub highlighting today.  e.g.

```fsharp
let foo = "123"
let ``foo bar`` = "123"

module Foo = 
    ()
module ``Foo Bar`` = 
    ()
```

**Comment by guillermooo** [comment]
Sublime will start using .sublime-syntax instead.

**Comment by rneatherway** [comment]
I have submitted a [PR](https://github.com/github/linguist/pull/2445) to use the definition in the https://github.com/fsprojects/atom-fsharp repository, which I think handles this case.
