### ISSUE TITLE
Underscores in identifiers colored as wildcards in GitHub highlighting

### ISSUE THREAD

**Issue by latkin** [fsharp/fsharpbinding#886]
```fsharp
let my_func_name_here () = ()  // good coloring here
my_func_name_here ()  // underscores getting inappropriate special coloring here
```

**Comment by 7sharp9** [comment]
Is this for sublime text, or rather a bug in that code?

**Comment by latkin** [comment]
? I don't understand.  This is for GH in particular, though my understanding is that it's the same definition files for Sublime.

**Comment by 7sharp9** [comment]
Yeah this repo is used for Xamarin Studio, Emacs, Sublime, just wanted to confirm so I could tag :-)

**Comment by guillermooo** [comment]
Sublime will start using the new .sublime-syntax, so I would suggest to untag.

**Comment by rneatherway** [comment]
I have submitted a [PR](https://github.com/github/linguist/pull/2445) to use the definition in the https://github.com/fsprojects/atom-fsharp repository, which I think handles this case.
