### ISSUE TITLE
Xbuild fails for Vim on OSX

### ISSUE THREAD

**Issue by wonbyte** [fsharp/fsharpbinding#889]
~/s/g/f/vim git:master ❯❯❯ make install
mkdir -p /Users/gps/src/github.com/fsharpbinding/vim/ftplugin/bin
mozroots --import --sync --quiet
xbuild /Users/gps/src/github.com/fsharpbinding/FSharp.AutoComplete/FSharp.AutoComplete.fsproj /property:OutputPath="/Users/gps/src/github.com/fsharpbinding/vim/ftplugin/bin"
XBuild Engine Version 12.0
Mono, Version 3.10.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 12/18/2014 8:54:26 PM.
__________________________________________________
Project "/Users/gps/src/github.com/fsharpbinding/FSharp.AutoComplete/FSharp.AutoComplete.fsproj" (default target(s)):
/Users/gps/src/github.com/fsharpbinding/FSharp.AutoComplete/FSharp.AutoComplete.fsproj: error : Target named 'Build' not found in the project.
Done building project "/Users/gps/src/github.com/fsharpbinding/FSharp.AutoComplete/FSharp.AutoComplete.fsproj".-- FAILED

Build FAILED.
Errors:

/Users/gps/src/github.com/fsharpbinding/FSharp.AutoComplete/FSharp.AutoComplete.fsproj (default targets) ->

	/Users/gps/src/github.com/fsharpbinding/FSharp.AutoComplete/FSharp.AutoComplete.fsproj: error : Target named 'Build' not found in the project.

	 0 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:00.0567340
make: *** [/Users/gps/src/github.com/fsharpbinding/vim/ftplugin/bin/fsautocomplete.exe] Error 1

**Comment by kjnilsson** [comment]
Hi - Any update on this @wonbyte ?

**Comment by wonbyte** [comment]
@kjnilsson will let you know this weekend. Sorry for the delay. Holidays have been busy

**Comment by wonbyte** [comment]
Hi @kjnilsson @rneatherway Here is an output of build /v:diag https://gist.github.com/wonbyte/cb0a3f3fbbcbc1ed2ef6

**Comment by kjnilsson** [comment]
yes it isn't finding the Microsoft.FSharp.Targets file where the build target is defined. Could you scan your harddrive for this file to see where it has been put (if anywhere at all).

**Comment by rneatherway** [comment]
It seems like a bug in the homebrew installation. @wonbyte, have you been able to build any F# project? fsharpi will work independently of xbuild, which is part of Mono and the F# install has to drop a new Targets file in the right place so that xbuild knows how to compile F# files.

You mentioned setting MONO_GAC_PREFIX. This shouldn't be required with a standard installation. What made you decide to set that variable?

**Comment by kjnilsson** [comment]
I agree with @rneatherway this seems like a homebrew issue - I am not sure how homebrew is managed but could you raise this issue with them and post a link to it in here?

The simplest way to get this working would be to uninstall mono and fsharp using brew and install XS and let XS install mono and fsharp for you. At least it should work correctly then. XS is good to have around for managing solutions and projects anyway.

**Comment by ticviking** [comment]
I just tried uninstalling the homebrew mono, and installing XS and it appears to have allowed this to work without error.

@rneatherway homebrew suggests that 
>    To use the assemblies from other formulae you need to set:
>     `export MONO_GAC_PREFIX="#{HOMEBREW_PREFIX}"`

I am getting a very similar error to @wonbyte when I try to run it with the homebrew mono, but have very little idea what parts of our error message are relevant to debugging the issue.

**Comment by haf** [comment]
Relevant:

https://github.com/Homebrew/homebrew/pull/36651

https://github.com/Homebrew/homebrew/pull/36764

**Comment by haf** [comment]
The error in this thread is due to bad .Targets paths, like linked in #36651.

**Comment by kjnilsson** [comment]
Thansk @haf ! Given 36651 has been closed I suggest we close this issue as well? Anyone disagree? :)

**Comment by haf** [comment]
Disagree: see https://github.com/fsharp/fsharp/issues/378#issuecomment-85079490

Would be good to close if you can verify that the problem has been fixed though. I can't guarantee the .Targets issue is absolutely *necessarily triggered* for this to occur.

**Comment by proger** [comment]
I'm having same problems with (just poured from bottles with a fresh homebrew upgrade — no install errors)
```
% brew info mono
mono: stable 3.12.1 (bottled)
http://www.mono-project.com/
/usr/local/Cellar/mono/3.12.1 (1131 files, 219M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mono.rb
==> Caveats
To use the assemblies from other formulae you need to set:
  export MONO_GAC_PREFIX="/usr/local"
% brew info fsharp
fsharp: stable 3.1.1.31 (bottled)
http://fsharp.org/
/usr/local/Cellar/fsharp/3.1.1.31 (61 files, 24M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fsharp.rb
==> Dependencies
Build: automake ✔, autoconf ✔, pkg-config ✔
Required: mono ✔
==> Caveats
To run programs built with fsharpc you need to set:
  export MONO_GAC_PREFIX="/usr/local"
```

**Comment by proger** [comment]
Just in case added a [fresh rebuild log for fsharp](https://gist.github.com/bd4bcb1372f169680236).

**Comment by haf** [comment]
ping @dsyme logs forthcoming! =)

**Comment by rneatherway** [comment]
Closing as this is not a Vim bug and this repo has been split up into its consituent parts. Discussion is better at https://github.com/fsharp/fsharp/issues/378 or similar.
