### ISSUE TITLE
vim - can't go to declaration when buffer is dirty

### ISSUE THREAD

**Issue by kjnilsson** [fsharp/fsharpbinding#922]
if you use leader+ d to go to a declaration and the buffer has not been saved, vim complains. 

we either need to save the buffer before the jump (simple) or open in another tab/window or detect the if the target is in the current file and simple move the cursor rather than using :e.

perhaps one for @wangzq ? :)

**Comment by wangzq** [comment]
I have been there: http://stackoverflow.com/questions/102384/using-vims-tabs-like-buffers

in short, you need to have "set hidden" in your vimrc and this is no longer a problem, :)

**Comment by kjnilsson** [comment]
ah ok thanks that would "Fix it" - I am not sure about having behaviour in the plugin that requires custom .vimrc settings unless it is well documented. Perhaps we should check if hidden is set and if not do a write before doing the jump? I'd like as many things as possible to just work without too much customisation.

**Comment by wangzq** [comment]
how about use try/catch and fallback to tab when the ":edit" fails?

**Comment by kjnilsson** [comment]
The simplest solution is probably just to check if hidden is set - if not then write the buffer before the :edit. At least then it will work even if a user hasn't set hidden.

**Comment by wangzq** [comment]
I am not sure; personally I don't like a tool to automatically save the
file for me, also, what if the file is new? Before I discovered the "set
hidden" option I was also struggling of the seems strange behavior of not
able to switch to another buffer without saving current buffer, but after
that I almost never need to use the tab feature again.

**Comment by kjnilsson** [comment]
having thought about it :set hidden is fine for now. Thanks for talking it through with me. :)
