### ISSUE TITLE
Autocompletion not working on Emacs 24.4+ on Windows

### ISSUE THREAD

**Issue by ane** [fsharp/fsharpbinding#923]
*Basic information*
OS: Windows 8.1
Emacs: 24.4.1
Visual Studio: 2015 Preview

Autocompletion at point `C-c C-.` or *anything* doesn't work even though projects load properly.

 I **think** I know why: in Emacs 24.4, on Windows, a `buffer-file-name` evaluates with **forward slashes**, so when I open `C:\fsharpbinding\emacs\test\Test1\Program.fs`, emacs sees this as `C:/fsharpbinding/emacs/test7Test1/Program.fs`.

But **fsharpcomplete** in its JSON returns files with escaped backslashes, as a result, in [fsharp-mode-completion.el:151](https://github.com/fsharp/fsharpbinding/blob/master/emacs/fsharp-mode-completion.el#L151), where the filename is returned, it is matched against incorrectly slashed directories. 

Adding a `convert-standard-filename` to wrap the call to `file-true-name` seems to fix it for me, but I don't know whether this is the right choice. It seems for some reason Emacs provides forward slashes now on Windows, while the F# fsautocomplete program uses the system defaults.

**Comment by rneatherway** [comment]
Thanks for reporting this issue. We should try to get it fixed soon and put out a new release on MELPA.

Your suggestion of using `convert-standard-filename` seems good. I am interested in when this problem arose though. The AppVeyor build is using Emacs 24.4, and the tests have previously passed on my machine with that version. Did this only start happening with Emacs 24.4.1?

**Comment by ane** [comment]
I'm afraid I don't know, since I tried this plugin for the first time yesterday, and 24.4.1 happened to be the version I was using. On my OSX machine it seemed to work fine using Mono and Emacs 24.4. 

You can test it yourself, open a file on Windows and then `M-:` and type `buffer-file-name`. If it returns forward slashes it won't work.

**Comment by rneatherway** [comment]
It looks like a general problem with Windows, and because the integration tests don't run properly on AppVeyor I didn't notice.

I've pushed a suggested fix at https://github.com/rneatherway/fsharpbinding/tree/issue923, would you mind giving it a try? You can just replace the fsharp-mode-completion.el file with the version from that branch.

**Comment by ane** [comment]
Seems to work! Replaced it directly in the ELPA-handled fsharp-mode directly, compiled it to bytecode, restarted emacs and loaded a F# file. Tooltips galore.

**Comment by rneatherway** [comment]
Great, this should be fixed by #934 and now up on MELPA. Let me know if you have any more trouble.
