### ISSUE TITLE
monodevelop install problem on ubuntu

### ISSUE THREAD

**Issue by jots** [fsharp/fsharpbinding#938]
I am new to monodevelop and f#.  trying to install f# language bindings for monodevelop on ubuntu 14.04 for monodevelop 5.7 

$ ./configure.sh 
$ make 
[everything good so far]
$ make install

rm -fr pack/5.8.0/mac-linux/Debug
mono '/usr/lib/monodevelop/bin/mdtool.exe' setup pack bin/mac-linux/Debug/FSharpBinding.dll -d:pack/5.8.0/mac-linux/Debug
MonoDevelop Add-in Setup Utility
ERROR: There was an error while scanning assembly: /home/joe/fsharp/fsharpbinding/monodevelop/bin/mac-linux/Debug/FSharpBinding.dll (The add-in configuration file is invalid: 'Extension' is expected  Line 521, position 8.)
ERROR: Could not read add-in file: bin/mac-linux/Debug/FSharpBinding.dll
mono '/usr/lib/monodevelop/bin/mdtool.exe' setup install -y pack/5.8.0/mac-linux/Debug/MonoDevelop.FSharpBinding_5.8.0.mpack 
MonoDevelop Add-in Setup Utility
The addin 'pack/5.8.0/mac-linux/Debug/MonoDevelop.FSharpBinding_5.8.0.mpack' is not available for install.
make: *** [install] Error 255

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#36
