### ISSUE TITLE
Need an explicit reference to FSharp.Core.dll

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/fsharpbinding#949]
This morning I encounter a strange bug. I have a projet wokring with both Visual Studio and Xamarin Studio.

Also, this project is working with fsharp-mode under Emacs. However under Windows, I need to add explicitly a reference to `FSharp.Core` otherwise I got this error :

```
1423134557.6803503: Received 'ERROR' message of length 65
1423134557.8303504: {"Kind":"errors","Data":[{"StartLine":0,"StartLineAlternate":1,"EndLine":0,"EndLineAlternate":1,"StartColumn":0,"EndColumn":80,"Severity":"Error","Message":"internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core.dll'","Subcategory":"typecheck","FileName":"startup"},{"StartLine":0,"StartLineAlternate":1,"EndLine":0,"EndLineAlternate":1,"StartColumn":0,"EndColumn":80,"Severity":"Error","Message":"Unable to find the file 'FSharp.Core.dll' in any of\n C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\n d:\\Users\\mmangel\\Documents\\_working\\_personnel\\1-Dev\\shadaenlab\\ShadaenSite\n C:\\Program Files (x86)\\Microsoft SDKs\\F#\\3.1\\Framework\\v4.0\\","Subcategory":"typecheck","FileName":"unknown"}]}
```

I tested it under two windows. One is windows Seven and second is Windows 10.

Not sure if it's a bug or not.

**Comment by rneatherway** [comment]
What version of F# do you have installed? Is FSharp.Core present in the
mentioned directories?

**Comment by MangelMaxime** [comment]
I'm using F# 3.1.

Not it's not present in any of the mentioned directories.

But what I found strange is that in my *.fsproj file I just added this line : 
```
<Reference Include="FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
```

According to this [SO post](http://stackoverflow.com/questions/20332046/correct-version-of-fsharp-core) the reference is present by default here `%ProgramFiles(x86)%\Reference Assemblies\Microsoft\FSharp` which is true in my case.

I don't know if we should use this directory or take the dll from NuGet.

**Comment by rneatherway** [comment]
Does it work in Xamarin Studio on Windows as well? It is rather strange but unfortunately MS decided to include FSharp.Core implicitly and guessing where it lives today is like playing whack a mole. You could try looking at https://github.com/fsharp/fsharpbinding/blob/master/FSharp.CompilerBinding/CompilerLocationUtils.fs

**Comment by 7sharp9** [comment]
Xamarin Studio explicitly adds a reference to FSharp.Core if one is not specified, as to mscorlib

**Comment by rneatherway** [comment]
Is that handled differently in the Xamarin fsharpbinding from fsautocomplete, or do they both use the `CompilerLocationUtils.fs` support?

**Comment by 7sharp9** [comment]
TBF I cant remember, see https://github.com/fsharp/fsharpbinding/blob/f8dd50c35cb775cf2db0bf10b77c54093004eec2/monodevelop/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs#L84

**Comment by rneatherway** [comment]
This is closed in favour of https://github.com/fsharp/FSharp.AutoComplete/issues/12
