### ISSUE TITLE
Multiline comments with `//` in them before closing `*)` are broken in GitHub colorization

### ISSUE THREAD

**Issue by latkin** [fsharp/fsharpbinding#953]
I noticed that the bottom ~75% of https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/build.fs#L973 is incorrectly greyed out.

Looking at the point where it starts, my hunch is that if a `//` sequence is inside a multi-line comment `(* ... *)` it somehow causes the close of the multiline comment to be ignored.

![image](https://cloud.githubusercontent.com/assets/5943573/6359418/de03dc68-bc27-11e4-93da-8f7b56437dbe.png)

**Comment by rojepp** [comment]
```fsharp
let a = 123
(* narrowing it down
  multiline comment // is fine
*)
let b = 23
(* things seem to break when // is on the same line as comment close -> *)
let c = 3
```

**Comment by rojepp** [comment]
@latkin Hey, cool, its been picked up by Github already! https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/build.fs#L973

**Comment by latkin** [comment]
:sparkles:
