### ISSUE TITLE
Can't undo a paste into F# 

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#954]
Repro:
```fsharp
     let date = DateTime.Now.ToString()
     let padded = date.PadRight
```

* Paste the snippet above *into the top of*  an F# file, one or several lines, doesn't matter.
* Undo (Cmd-Z)

Paste is not undone. This works in C#. Tested on OSX. 
After pasting into the top of a file, some state is corrupted and undo no longer works anywhere. 
This only seems to happen when code being pasted starts with whitespace.

**Comment by 7sharp9** [comment]
I cant replicate on XS 5.7.2

**Comment by rojepp** [comment]
I'm on 5.7.2, build 2. 
I've narrowed it down some and updated the repro steps.

**Comment by 7sharp9** [comment]
I cant replicate that either :-)

**Comment by rojepp** [comment]
Updated again, could you try it with the code snippet above (leading white space)?

**Comment by rojepp** [comment]
If there is leading space, and you paste in the middle of a file, but not at column 1, same behaviour. Subtle, but it happens frequently for me.

**Comment by 7sharp9** [comment]
I have no such issues, the only thing I get often is the indentation is out on a paste.

**Comment by rojepp** [comment]
I think this may be caused by the indenter throwing. XS catches the exception and forgets to do something, leaving undo corrupt.

**Comment by 7sharp9** [comment]
I put a catch in the new roslyn branch indenter yesterday `just in case`

**Comment by rojepp** [comment]
I debugged it, and yes, the indenter throws when pasting code with leading whitespace, and Xamarin silently catches it. Avoiding the exception does fix the issue for me, and may also avoid other subtle bugs. Want a PR?

**Comment by 7sharp9** [comment]
Sure a PR would be great. Extension points shouldn't kill XS so they have to be caught, they are also logged too.
