### ISSUE TITLE
[monodevelop] Wrong symbol highlighting in Find all references results

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/fsharpbinding#962]
![image](https://cloud.githubusercontent.com/assets/873919/6426235/a2324020-bf61-11e4-91ca-a62eaa946cee.png)

**Comment by 7sharp9** [comment]
I think thats an upstream issue in MonoDevelop, some seem to be out by two, others by one.

**Comment by 7sharp9** [comment]
Seems to be resolved in FSharpMDXS now.
