### ISSUE TITLE
Rename doesn't work in script file

### ISSUE THREAD

**Issue by rojepp** [fsharp/fsharpbinding#974]
![rename](https://cloud.githubusercontent.com/assets/445888/6709354/0b64fcca-cd79-11e4-9d47-f6a96ee9070f.gif)

This is in a script opened without a project. Rename command is available, but nothing happens when executing it.

**Comment by 7sharp9** [comment]
This will either be fixed in the 5.9. branch or resolved in the new repo where rename is quite different..

**Comment by 7sharp9** [comment]
Possibly this could be an FCS issue if the symbol is not found.

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#18
