### ISSUE TITLE
Should generate /Release/ dir by default

### ISSUE THREAD

**Issue by knocte** [fsharp/fsharpbinding#981]
If there is an optional `--debug` flag (as specified in the README file) that the user can pass to `configure.sh`, then the generated files by the build should end up in a folder called `monodevelop/bin/mac-linux/Release/`, not `Debug` like it happens now when not passing the flag.

**Comment by 7sharp9** [comment]
As far as I know release is never used.  Unless you manually install.

**Comment by 7sharp9** [comment]
The F# addin is moving to fsharp/fsharpMDXS so any related issues should go over there.

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#34
