### ISSUE TITLE
[github] Single-line comments incorrectly highlighted when *) present

### ISSUE THREAD

**Issue by latkin** [fsharp/fsharpbinding#987]
When `*)` is present in a single-line `//` comment, that comment line gets colored incorrectly.

```fsharp
// here is a normal comment
// here is a busted *) comment 
```

**Comment by guillermooo** [comment]
Sublime will start using .sublime-syntax format, so untagging.

**Comment by rneatherway** [comment]
@Krzysztof-Cieslak does this work in Atom?

**Comment by Krzysztof-Cieslak** [comment]
Nope, same result as in original post

**Comment by rneatherway** [comment]
Issue opened at https://github.com/fsprojects/atom-fsharp/issues/58
