### ISSUE TITLE
[github] Escaped double quotes in verbatim strings conflict with triple-quoted strings

### ISSUE THREAD

**Issue by latkin** [fsharp/fsharpbinding#988]
Inside of a verbatim `@" "` string, literal double quotes are escaped by another double quote, which means it's valid to end a string in code with a triple quote:

![image](https://cloud.githubusercontent.com/assets/5943573/7052958/c9d39464-dde6-11e4-80e9-2aa59fe97039.png)

This is not handled correctly in github/sublime (I assume the issue is some collision with handling of verbatim triple-quoted strings).  Seems like it's only closing triple-quote that has a problem, leading triple-quote looks ok.

```fsharp
let s0 = @"xyz"" "  // ok
```
```fsharp
let s1 = @"xyz"""   // oops
```
```fsharp
let s2 = @"""xyz"   // ok
```
```fsharp
let s3 = @" ""xyz"  // ok
```

**Comment by guillermooo** [comment]
Sublime will start using the new .sublime-syntax, so I would suggest to untag.

**Comment by rneatherway** [comment]
@Krzysztof-Cieslak does this work in Atom?

**Comment by Krzysztof-Cieslak** [comment]
Same result as in original post for each line separately. Worth mention that it also has some problems when put together.

![image](https://cloud.githubusercontent.com/assets/5427083/8064696/a21c4c00-0edc-11e5-86f0-6d5466f026b4.png)
