### ISSUE TITLE
could not import MSBuildExtensionPath32 in Monodevelop

### ISSUE THREAD

**Issue by Pipsy** [fsharp/fsharpbinding#998]
When I build a project in Monodevelop(Ubuntu 14.10) I get this message.
Anybody an idea what is wrong?
could not import MSBuildExtensionPath32\..\..\F#\3.0\Framework\v4.0\Microsoft.Fsharp.Targets

**Comment by knocte** [comment]
what version of mono?

**Comment by Pipsy** [comment]
Andres version 5.5

**Comment by knocte** [comment]
I asked the version of mono, not the version of monodevelop :)

**Comment by Pipsy** [comment]
3.2.8

**Comment by 7sharp9** [comment]
Is F# installed?

**Comment by Pipsy** [comment]
Yes- David

**Comment by knocte** [comment]
How did you install fsharp and mono?

**Comment by Pipsy** [comment]
Andres; monodevelop 5.5, mono 3.2.8, gtk 2.24.27; I installed via Dash
except f# language bindings via Tools, add_in manager. Gr Willem

**Comment by knocte** [comment]
Do you have the package "mono-xbuild" installed?

**Comment by Pipsy** [comment]
Yes, that is installed

**Comment by 7sharp9** [comment]
This issue was moved to fsharp/xamarin-monodevelop-fsharp-addin#33
